version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tech_spec_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user123
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tech_spec_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: